version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install

artifacts:
  files:
    - '**/LoginWebApp-1.war'
    - 'appspec.yaml'
  discard-paths: yes
